version: '3.5'

volumes:
  user-db-data:

networks:
  esbay-network:
    driver: bridge

services:
  ms-l1:
    build:
      context: ./src/micro_services/lab1
    ports:
      - 8082:5000
    depends_on:
      - user_db
    restart: always
    networks:
      - esbay-network

  ms-l21:
    build:
      context: ./src/micro_services/lab2/lab2.1
    ports:
      - 8082:5000
    depends_on:
      - user_db
    restart: always
    networks:
      - esbay-network

  ms-l22:
    build:
      context: ./src/micro_services/lab2/lab2.2
    ports:
      - 8082:5000
    depends_on:
      - user_db
    restart: always
    networks:
      - esbay-network

  ms-l31:
    build:
      context: ./src/micro_services/lab3/lab3.1
    ports:
      - 8082:5000
    depends_on:
      - user_db
    restart: always
    networks:
      - esbay-network
      
  ms-l32:
    build:
      context: ./src/micro_services/lab3/lab3.2
    ports:
      - 8082:5000
    depends_on:
      - user_db
    restart: always
    networks:
      - esbay-network

  user_db:
    image: mysql:5.7.22
    volumes:
      - user-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=user
    restart: always
    networks:
      - esbay-network
