FROM python:3.7-alpine  

COPY ./requirements.txt ./requirements.txt  
WORKDIR ./  

RUN apk add --no-cache --update \
    build-base \
    bash \
    curl \
    gcc \      
    libc-dev \      
    mariadb-dev \      
    musl-dev \      
    linux-headers \   
    && pip install --upgrade pip \   
    && pip install -r requirements.txt  

ENV FLASK_RUN_HOST=0.0.0.0 
ENV FLASK_ENV=development 
EXPOSE 5000  

COPY ./src/micro_services/lab3/lab 3.2/ /app/micro_services/lab3/lab 3.2/ 
CMD ["python", "/micro_services/lab3/lab 3.2/esbay/user-ms/app/app.py & /micro_services/lab3/lab 3.2/esbay/products-ms/app/app.py"]